- name: Install Docker on Vagrant Machines (CentOS)
  hosts: machines
  become: yes  # Run tasks as root
  
  tasks:
    - name: Install required system packages
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      
    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes


    - name: Add vagrant user to the Docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Disable SELinux (Optional)
      command: setenforce 0
      ignore_errors: yes
      become: yes
 
- name: Install Python Docker SDK
  hosts: machines
  become: yes  # Run as root
  tasks:
    - name: Install Python3 and pip using DNF
      dnf:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

- name: Deploy Docker Container
  hosts: machines
  become: yes
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: hebamaher/weather-app
        source: pull

    - name: Run Docker container
      docker_container:
        name: weatherapp-container
        image: hebamaher/weather-app
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
